apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudstore-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /api/account
          pathType: Prefix
          backend:
            service:
              name: userhandle-service
              port:
                number: 5001
