apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
  labels:
    app: reviews   
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reviews  
  template:
    metadata:
      labels:
        app: reviews  
    spec:
      containers:
        - name: reviews 
          image: navinshrinivas/cloudstore_reviews 
          ports:
          - containerPort: 5004 
          imagePullPolicy: Always
          env:
          - name: ENVIRONMENT
            value: "development"
          - name: PORT
            value: "5004"
          - name: ALLOWED_ORIGINS
            value: "http://localhost:3000,http://localhost:5002,http://localhost:5003"
          - name: USERHANDLE_ADDRESS
            value: "http://localhost:5001"
          - name: DATABASE_NAME
            value: "cloudstore"
          - name: DATABASE_HOST
            value: "test.mysql.database.azure.com"
          - name: DATABASE_PORT
            value: "3306"
          - name: DATABASE_USERNAME
            value: "cloudadmin"
          - name: DATABASE_PASSWORD
            value: "!Admin123"
---
apiVersion: v1
kind: Service
metadata:
  name: reviews-service 
spec:
  selector:
    app: reviews 
  ports:
  - port: 5004 
    targetPort: 5004 
  type: LoadBalancer
