apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  labels:
    app: products 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: products 
  template:
    metadata:
      labels:
        app: products 
    spec:
      containers:
        - name: products 
          image: navinshrinivas/cloudstore_product
          ports:
          - containerPort: 5002
          imagePullPolicy: Always
          env:
          - name: ENVIRONMENT
            value: "development"
          - name: PORT
            value: "5002"
          - name: ALLOWED_ORIGINS
            value: "http://localhost:3000"
          - name: USERHANDLE_ADDRESS
            value: "http://localhost:5001"
          - name: DATABASE_NAME
            value: "cloudstore"
          - name: DATABASE_HOST
            value: "test.mysql.database.azure.com"
          - name: DATABASE_PORT
            value: "3306"
          - name: DATABASE_USERNAME
            value: "cloudadmin"
          - name: DATABASE_PASSWORD
            value: "!Admin123"
---
apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  selector:
    app: products
  ports:
  - port: 5002
    targetPort: 5002 
  type: LoadBalancer
